'use client';

import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'bn' | 'te' | 'mr' | 'ta' | 'gu' | 'kn' | 'ml' | 'pa' | 'or';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: 'Health Summarizer',
    tagline: 'Privacy-Safe Health Record Summarizer',
    subtitle: 'Summarize medical reports without exposing personal data.',
    startSummarizing: 'Start Summarizing',
    viewDemo: 'View Demo',
    home: 'Home',
    features: 'Features',
    howItWorks: 'How it Works',
    demo: 'Demo',
    security: 'Security',
    about: 'About',
    login: 'Login',
    settings: 'Settings',
    profile: 'Profile',
    selectLanguage: 'Select Language',
    trustBanner: 'We never store raw medical records.',
    trustSubtext: 'Only redacted summaries are processed and only summaries can be saved.',
    chipZeroStorage: 'Zero Raw Data Storage',
    chipRedaction: 'Client-side Redaction',
    chipCitations: 'Explainable Citations',
    dashboard: 'Dashboard',
    dashboardTitle: 'Dashboard',
    dashboardSubtitle: 'Placeholder dashboard for Health Summarizer (HT-3).',
    summarizeTitle: 'Secure Summarization',
    summarizeSubtitle: 'Upload a report (PDF or text). Redaction happens client-side.',
    uploadReport: 'Upload Report',
    upload: 'Upload',
    uploadNote: 'This is a placeholder upload area. In a full implementation, files would be redacted client-side before any processing.',
    product: 'Product',
    resources: 'Resources',
    legal: 'Legal',
    privacyPolicy: 'Privacy Policy (placeholder)',
    contactFooter: 'Contact (placeholder)',
    github: 'GitHub (placeholder)',
    terms: 'Terms (placeholder)',
    data: 'Data (placeholder)',
    footerCopyright: '© 2026 Health Summarizer. Built for HT-3.',
    contactPage: 'Contact Page',
    downloadPDF: 'Download PDF',
    share: 'Share',
    // How it Works section
    howItWorksSubtitle: 'Simple, privacy-first workflow.',
    step1Title: 'Upload Report',
    step1Desc: 'PDF or text upload in seconds.',
    step2Title: 'Auto Redaction',
    step2Desc: 'PHI is masked client-side before processing.',
    step3Title: 'AI Summary',
    step3Desc: 'Structured, concise summaries.',
    step4Title: 'Citations',
    step4Desc: 'Section-based citations for explainability.',
    // Features section
    featuresSubtitle: 'Privacy-first features for healthcare workflows.',
    featureClientSide: 'Client-Side Privacy',
    featureClientSideDesc: 'Redaction happens locally before any upload.',
    featureZeroStorage: 'Zero Raw Data Storage',
    featureZeroStorageDesc: 'Raw records are never stored on our servers.',
    featureExplainable: 'Explainable Summaries',
    featureExplainableDesc: 'Citations link summary lines to source sections.',
    featureExportPDF: 'Export Summary PDF',
    featureExportPDFDesc: 'Download clean, patient-friendly PDFs.',
    featurePatientMode: 'Patient-friendly Mode',
    featurePatientModeDesc: 'Summaries tailored to patient understanding.',
    featureOffline: 'Offline / Local Mode',
    featureOfflineDesc: 'Optional local processing for extra privacy.',
    mutationA: 'Mutation A',
    mutationB: 'Mutation B',
    // Demo section
    demoTitle: 'Demo / Preview',
    demoSubtitle: 'Synthetic, redacted examples only.',
    redactedInput: 'Redacted Input (example)',
    generatedSummary: 'Generated Summary',
    demoNote: 'Demo uses synthetic text only.',
    demoText1: 'High blood sugar detected.',
    demoText2: 'Metformin listed in medications.',
    demoText3: 'Follow-up recommended in 3 months.',
    demoTagLabs: '[Labs]',
    demoTagMeds: '[Medications]',
    demoTagPlan: '[Plan]',
    // Who Can Use section
    whoCanUseTitle: 'Who Can Use It',
    whoCanUseSubtitle: 'Designed for healthcare teams and learners.',
    userDoctors: 'Doctors',
    userDoctorsDesc: 'Quick clinical summaries',
    userClinics: 'Clinics',
    userClinicsDesc: 'Streamline charting',
    userPatients: 'Patients',
    userPatientsDesc: 'Patient-friendly summaries',
    userStudents: 'Students',
    userStudentsDesc: 'Research & learning',
    // Security section
    securityTitle: 'Security & Compliance',
    securitySubtitle: 'Privacy-first design — practical safeguards without legal claims.',
    security1Title: 'PHI detector blocks sensitive output',
    security1Desc: 'Automated filters reduce leakage risk.',
    security2Title: 'No raw-text logging',
    security2Desc: 'Only redacted content is processed server-side.',
    security3Title: 'Encrypted summary storage (optional)',
    security3Desc: 'User-controlled encryption settings.',
    security4Title: 'User-controlled deletion',
    security4Desc: 'Users may delete saved summaries at any time.',
    // Final CTA
    ctaTitle: 'Ready to summarize safely?',
    ctaSubtitle: 'Start with synthetic demo data or upload your own (redacted client-side).',
    ctaButton: 'Try Secure Summarization',
    ctaSecondary: 'Go to Dashboard',
    summaryPreview: 'Summary preview',
    syntheticNote: 'redacted • synthetic',
    // Summary page
    healthRecordSummary: 'Health Record Summary',
    medicalSummary: 'Medical Summary',
    medicalSummarySubtext: 'AI-powered analysis of your health record',
    keyFindings: 'Key Findings',
    currentTreatment: 'Current Treatment',
    followUpPlan: 'Follow-up Plan',
    summaryPoint1: 'Blood glucose levels were elevated over 3 consecutive fasting readings, indicating potential diabetes management needs.',
    summaryPoint2: 'Current medication includes Metformin 500mg taken daily for blood sugar control.',
    summaryPoint3: 'No known allergies documented in the record.',
    treatmentPoint1: 'Patient is on Metformin 500mg daily regimen.',
    treatmentPoint2: 'Regular monitoring of blood glucose levels is ongoing.',
    treatmentPoint3: 'No adverse reactions reported with current medication.',
    followUpPoint1: 'Follow-up appointment recommended to assess treatment effectiveness.',
    followUpPoint2: 'Continued monitoring of blood sugar levels advised.',
    followUpPoint3: 'Review medication dosage if needed during next visit.',
    aiGenerated: 'AI-generated summary',
    complete: 'Complete',
    generating: 'Generating...',
    copy: 'Copy',
    copied: 'Copied!',
    export: 'Export',
    recommendations: 'Recommendations',
    listen: 'Listen',
    stop: 'Stop',
    // Search page
    searchPatient: 'Search Patient by UID',
    searchDescription: 'Enter the patient\'s unique ID to view their records',
    patientUID: 'Patient UID',
    enterUID: 'Enter UID (e.g., PAT001)',
    search: 'Search',
    searching: 'Searching...',
    enterValidUID: 'Please enter a valid UID',
    patientNotFound: 'No patient found with this UID',
    searchError: 'Error searching for patient',
    patientDetails: 'Patient Details',
    patientName: 'Patient Name',
    age: 'Age',
    gender: 'Gender',
    contact: 'Contact',
    lastVisit: 'Last Visit',
    medicalHistory: 'Medical History',
    viewSummary: 'View Health Summary',
    viewRecommendations: 'View Recommendations',
    currentDiagnosis: 'Current Diagnosis',
    backToDashboard: 'Back to Dashboard',
  },
  hi: {
    appName: 'स्वास्थ्य सारांशक',
    tagline: 'गोपनीयता-सुरक्षित स्वास्थ्य रिकॉर्ड सारांशक',
    subtitle: 'व्यक्तिगत डेटा उजागर किए बिना चिकित्सा रिपोर्ट सारांशित करें।',
    startSummarizing: 'सारांश शुरू करें',
    viewDemo: 'डेमो देखें',
    home: 'होम',
    features: 'विशेषताएं',
    howItWorks: 'यह कैसे काम करता है',
    demo: 'डेमो',
    security: 'सुरक्षा',
    about: 'हमारे बारे में',
    login: 'लॉगिन',
    settings: 'सेटिंग्स',
    profile: 'प्रोफ़ाइल',
    selectLanguage: 'भाषा चुनें',
    trustBanner: 'हम कभी भी कच्चे चिकित्सा रिकॉर्ड संग्रहीत नहीं करते।',
    trustSubtext: 'केवल संपादित सारांश संसाधित किए जाते हैं।',
    chipZeroStorage: 'शून्य कच्चा डेटा संग्रहण',
    chipRedaction: 'क्लाइंट-साइड संपादन',
    chipCitations: 'व्याख्यात्मक उद्धरण',
    dashboard: 'डैशबोर्ड',
    dashboardTitle: 'डैशबोर्ड',
    dashboardSubtitle: 'स्वास्थ्य सारांशक (HT-3) के लिए प्लेसहोल्डर डैशबोर्ड।',
    summarizeTitle: 'सुरक्षित सारांश',
    summarizeSubtitle: 'रिपोर्ट अपलोड करें (PDF या पाठ)। संपादन क्लाइंट-साइड होता है।',
    uploadReport: 'रिपोर्ट अपलोड करें',
    upload: 'अपलोड करें',
    uploadNote: 'यह एक प्लेसहोल्डर अपलोड क्षेत्र है। पूर्ण कार्यान्वयन में, फ़ाइलें प्रसंस्करण से पहले क्लाइंट-साइड संपादित की जाएंगी।',
    product: 'उत्पाद',
    resources: 'संसाधन',
    legal: 'कानूनी',
    privacyPolicy: 'गोपनीयता नीति (प्लेसहोल्डर)',
    contactFooter: 'संपर्क (प्लेसहोल्डर)',
    github: 'GitHub (प्लेसहोल्डर)',
    terms: 'शर्तें (प्लेसहोल्डर)',
    data: 'डेटा (प्लेसहोल्डर)',
    footerCopyright: '© 2026 स्वास्थ्य सारांशक। HT-3 के लिए निर्मित।',
    contactPage: 'संपर्क पृष्ठ',
    downloadPDF: 'PDF डाउनलोड करें',
    share: 'साझा करें',
    // How it Works section
    howItWorksSubtitle: 'सरल, गोपनीयता-प्रथम वर्कफ़्लो।',
    step1Title: 'रिपोर्ट अपलोड करें',
    step1Desc: 'सेकंड में PDF या टेक्स्ट अपलोड।',
    step2Title: 'स्वत: संपादन',
    step2Desc: 'प्रसंस्करण से पहले PHI क्लाइंट-साइड पर मास्क किया जाता है।',
    step3Title: 'AI सारांश',
    step3Desc: 'संरचित, संक्षिप्त सारांश।',
    step4Title: 'उद्धरण',
    step4Desc: 'व्याख्या के लिए अनुभाग-आधारित उद्धरण।',
    // Features section
    featuresSubtitle: 'स्वास्थ्य वर्कफ़्लो के लिए गोपनीयता-प्रथम सुविधाएं।',
    featureClientSide: 'क्लाइंट-साइड गोपनीयता',
    featureClientSideDesc: 'किसी भी अपलोड से पहले स्थानीय रूप से संपादन होता है।',
    featureZeroStorage: 'शून्य कच्चा डेटा संग्रहण',
    featureZeroStorageDesc: 'कच्चे रिकॉर्ड कभी भी हमारे सर्वर पर संग्रहीत नहीं होते।',
    featureExplainable: 'व्याख्यात्मक सारांश',
    featureExplainableDesc: 'उद्धरण सारांश लाइनों को स्रोत अनुभागों से जोड़ते हैं।',
    featureExportPDF: 'सारांश PDF निर्यात करें',
    featureExportPDFDesc: 'साफ, रोगी-अनुकूल PDF डाउनलोड करें।',
    featurePatientMode: 'रोगी-अनुकूल मोड',
    featurePatientModeDesc: 'रोगी की समझ के अनुरूप सारांश।',
    featureOffline: 'ऑफलाइन / स्थानीय मोड',
    featureOfflineDesc: 'अतिरिक्त गोपनीयता के लिए वैकल्पिक स्थानीय प्रसंस्करण।',
    mutationA: 'म्यूटेशन A',
    mutationB: 'म्यूटेशन B',
    // Demo section
    demoTitle: 'डेमो / पूर्वावलोकन',
    demoSubtitle: 'केवल सिंथेटिक, संपादित उदाहरण।',
    redactedInput: 'संपादित इनपुट (उदाहरण)',
    generatedSummary: 'उत्पन्न सारांश',
    demoNote: 'डेमो केवल सिंथेटिक टेक्स्ट का उपयोग करता है।',
    demoText1: 'उच्च रक्त शर्करा का पता चला।',
    demoText2: 'दवाओं में मेटफॉर्मिन सूचीबद्ध।',
    demoText3: '3 महीने में फॉलो-अप की सिफारिश।',
    demoTagLabs: '[प्रयोगशाला]',
    demoTagMeds: '[दवाएं]',
    demoTagPlan: '[योजना]',
    // Who Can Use section
    whoCanUseTitle: 'इसका उपयोग कौन कर सकता है',
    whoCanUseSubtitle: 'स्वास्थ्य टीमों और शिक्षार्थियों के लिए डिज़ाइन किया गया।',
    userDoctors: 'डॉक्टर',
    userDoctorsDesc: 'त्वरित नैदानिक सारांश',
    userClinics: 'क्लीनिक',
    userClinicsDesc: 'चार्टिंग को सुव्यवस्थित करें',
    userPatients: 'रोगी',
    userPatientsDesc: 'रोगी-अनुकूल सारांश',
    userStudents: 'छात्र',
    userStudentsDesc: 'अनुसंधान और सीखना',
    // Security section
    securityTitle: 'सुरक्षा और अनुपालन',
    securitySubtitle: 'गोपनीयता-प्रथम डिज़ाइन — कानूनी दावों के बिना व्यावहारिक सुरक्षा।',
    security1Title: 'PHI डिटेक्टर संवेदनशील आउटपुट को ब्लॉक करता है',
    security1Desc: 'स्वचालित फ़िल्टर रिसाव जोखिम को कम करते हैं।',
    security2Title: 'कोई कच्चा-टेक्स्ट लॉगिंग नहीं',
    security2Desc: 'केवल संपादित सामग्री सर्वर-साइड पर संसाधित की जाती है।',
    security3Title: 'एन्क्रिप्टेड सारांश संग्रहण (वैकल्पिक)',
    security3Desc: 'उपयोगकर्ता-नियंत्रित एन्क्रिप्शन सेटिंग्स।',
    security4Title: 'उपयोगकर्ता-नियंत्रित विलोपन',
    security4Desc: 'उपयोगकर्ता किसी भी समय सहेजे गए सारांश हटा सकते हैं।',
    // Final CTA
    ctaTitle: 'सुरक्षित रूप से सारांशित करने के लिए तैयार?',
    ctaSubtitle: 'सिंथेटिक डेमो डेटा से शुरू करें या अपना खुद का अपलोड करें (क्लाइंट-साइड संपादित)।',
    ctaButton: 'सुरक्षित सारांश आज़माएं',
    ctaSecondary: 'डैशबोर्ड पर जाएं',
    summaryPreview: 'सारांश पूर्वावलोकन',
    syntheticNote: 'संपादित • सिंथेटिक',
    healthRecordSummary: 'स्वास्थ्य रिकॉर्ड सारांश',
    medicalSummary: 'चिकित्सा सारांश',
    medicalSummarySubtext: 'आपके स्वास्थ्य रिकॉर्ड का AI-संचालित विश्लेषण',
    keyFindings: 'मुख्य निष्कर्ष',
    currentTreatment: 'वर्तमान उपचार',
    followUpPlan: 'फॉलो-अप योजना',
    summaryPoint1: 'रक्त ग्लूकोज स्तर लगातार 3 उपवास रीडिंग में बढ़े हुए थे, जो संभावित मधुमेह प्रबंधन की आवश्यकता का संकेत देते हैं।',
    summaryPoint2: 'वर्तमान दवा में रक्त शर्करा नियंत्रण के लिए प्रतिदिन ली जाने वाली मेटफॉर्मिन 500mg शामिल है।',
    summaryPoint3: 'रिकॉर्ड में कोई ज्ञात एलर्जी दर्ज नहीं की गई।',
    treatmentPoint1: 'रोगी मेटफॉर्मिन 500mg दैनिक आहार पर है।',
    treatmentPoint2: 'रक्त ग्लूकोज स्तर की नियमित निगरानी चल रही है।',
    treatmentPoint3: 'वर्तमान दवा के साथ कोई प्रतिकूल प्रतिक्रिया नहीं बताई गई।',
    followUpPoint1: 'उपचार प्रभावशीलता का आकलन करने के लिए फॉलो-अप नियुक्ति की सिफारिश की जाती है।',
    followUpPoint2: 'रक्त शर्करा के स्तर की निरंतर निगरानी की सलाह दी जाती है।',
    followUpPoint3: 'अगली यात्रा के दौरान आवश्यकता पड़ने पर दवा की खुराक की समीक्षा करें।',
    aiGenerated: 'AI-जनित सारांश',
    complete: 'पूर्ण',
    generating: 'उत्पन्न हो रहा है...',
    copy: 'कॉपी करें',
    copied: 'कॉपी किया गया!',
    export: 'निर्यात करें',
    recommendations: 'सिफारिशें',
    listen: 'सुनें',
    stop: 'रोकें',
    // Search page
    searchPatient: 'UID द्वारा रोगी खोजें',
    searchDescription: 'उनके रिकॉर्ड देखने के लिए रोगी की अद्वितीय आईडी दर्ज करें',
    patientUID: 'रोगी UID',
    enterUID: 'UID दर्ज करें (उदा., PAT001)',
    search: 'खोजें',
    searching: 'खोज रहे हैं...',
    enterValidUID: 'कृपया एक मान्य UID दर्ज करें',
    patientNotFound: 'इस UID के साथ कोई रोगी नहीं मिला',
    searchError: 'रोगी खोजने में त्रुटि',
    patientDetails: 'रोगी विवरण',
    patientName: 'रोगी का नाम',
    age: 'आयु',
    gender: 'लिंग',
    contact: 'संपर्क',
    lastVisit: 'अंतिम मुलाकात',
    medicalHistory: 'चिकित्सा इतिहास',
    viewSummary: 'स्वास्थ्य सारांश देखें',
    viewRecommendations: 'सिफारिशें देखें',
    currentDiagnosis: 'वर्तमान निदान',
    backToDashboard: 'डैशबोर्ड पर वापस जाएं',
  },
  bn: {
    appName: 'স্বাস্থ্য সারসংক্ষেপকারী',
    tagline: 'গোপনীয়তা-নিরাপদ স্বাস্থ্য রেকর্ড সারসংক্ষেপ',
    subtitle: 'ব্যক্তিগত তথ্য প্রকাশ না করে চিকিৎসা রিপোর্ট সংক্ষিপ্ত করুন।',
    startSummarizing: 'সংক্ষিপ্তকরণ শুরু করুন',
    viewDemo: 'ডেমো দেখুন',
    home: 'হোম',
    features: 'বৈশিষ্ট্য',
    howItWorks: 'এটি কীভাবে কাজ করে',
    demo: 'ডেমো',
    security: 'নিরাপত্তা',
    about: 'আমাদের সম্পর্কে',
    login: 'লগইন',
    settings: 'সেটিংস',
    profile: 'প্রোফাইল',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    dashboard: 'ড্যাশবোর্ড',
    trustBanner: 'আমরা কখনও কাঁচা চিকিৎসা রেকর্ড সংরক্ষণ করি না।',
    trustSubtext: 'শুধুমাত্র সম্পাদিত সারসংক্ষেপ প্রক্রিয়া করা হয়।',
    chipZeroStorage: 'শূন্য কাঁচা ডেটা সংরক্ষণ',
    chipRedaction: 'ক্লায়েন্ট-সাইড সম্পাদনা',
    chipCitations: 'ব্যাখ্যাযোগ্য উদ্ধৃতি',
    product: 'পণ্য',
    resources: 'সম্পদ',
    legal: 'আইনি',
    privacyPolicy: 'গোপনীয়তা নীতি',
    contact: 'যোগাযোগ',
    github: 'GitHub',
    terms: 'শর্তাবলী',
    data: 'ডেটা',
    footerCopyright: '© 2026 স্বাস্থ্য সারসংক্ষেপকারী। সর্বস্বত্ব সংরক্ষিত।',
  },
  te: {
    appName: 'ఆరోగ్య సారాంశకర్త',
    tagline: 'గోప్యత-సురక్షిత ఆరోగ్య రికార్డు సారాంశం',
    subtitle: 'వ్యక్తిగత డేటాను బహిర్గతం చేయకుండా వైద్య నివేదికలను సంక్ષిప్తీకరించండి.',
    startSummarizing: 'సంక్ష��ప్తీకరణ ప్రారంభించండి',
    viewDemo: 'డెమో చూడండి',
    home: 'హోమ్',
    features: 'ఫీచర్లు',
    howItWorks: 'ఇది ఎలా పనిచేస్తుంది',
    demo: 'డెమో',
    security: 'భద్రత',
    about: 'మా గురించి',
    login: 'లాగిన్',
    settings: 'సెట్టింగ్లు',
    profile: 'ప్రోఫైల్',
    selectLanguage: 'భాషను ఎంచుకోండి',
    dashboard: 'డ్యాష్‌బోర్డ్',
    trustBanner: 'మేము ముడి వైద్య రికార్డులను ఎప్పుడూ నిల్వ చేయము.',
    trustSubtext: 'సవరించిన సారాంశాలు మాత్రమే ప్రాసెస్ చేయబడతాయి.',
    chipZeroStorage: 'సున్న ముడి డేటా నిల్వ',
    chipRedaction: 'క్లయింట్-సైడ్ సవరణ',
    chipCitations: 'వివరణాత్మక ఉల్లేఖనాలు',
    product: 'ఉత్పత్తి',
    resources: 'వనరులు',
    legal: 'చట్టపరమైన',
    privacyPolicy: 'గోప్యతా విధానం',
    contact: 'సంప్రదించండి',
    github: 'GitHub',
    terms: 'నియమాలు',
    data: 'డేటా',
    footerCopyright: '© 2026 ఆరోగ్య సారాంశకర్త। అన్ని హక్కులు సురక్షితం।',
  },
  mr: {
    appName: 'आरोग्य सारांशक',
    tagline: 'गोपनीयता-सुरक्षित आरोग्य रेकॉर्ड सारांशक',
    subtitle: 'वैयक्तिक डेटा उघड न करता वैद्यकीय अहवाल सारांशित करा।',
    startSummarizing: 'सारांश सुरू करा',
    viewDemo: 'डेमो पहा',
    home: 'होम',
    features: 'वैशिष्ट्ये',
    howItWorks: 'हे कसे कार्य करते',
    demo: 'डेमो',
    security: 'सुरक्षा',
    about: 'आम्हाला बद्दल',
    login: 'लॉगिन',
    settings: 'सेटिंग्ज',
    profile: 'प्रोफाइल',
    selectLanguage: 'भाषा निवडा',
    dashboard: 'डॅशबोर्ड',
    trustBanner: 'आम्ही कधीही कच्चे वैद्यकीय रेकॉर्ड साठवत नाही.',
    trustSubtext: 'फक्त संपादित सारांश प्रक्रिया केले जातात.',
    chipZeroStorage: 'शून्य कच्चा डेटा संचयन',
    chipRedaction: 'क्लायंट-साइड संपादन',
    chipCitations: 'स्पष्टीकरणात्मक उद्धरणे',
    product: 'उत्पादन',
    resources: 'संसाधने',
    legal: 'कायदेशीर',
    privacyPolicy: 'गोपनीयता धोरण',
    contact: 'संपर्क',
    github: 'GitHub',
    terms: 'अटी',
    data: 'डेटा',
    footerCopyright: '© 2026 आरोग्य सारांशक। सर्व हक्क राखीव।',
  },
  ta: {
    appName: 'சுகாதார சுருக்கி',
    tagline: 'தனியுரிமை-பாதுகாப்பான சுகாதார பதிவு சுருக்கம்',
    subtitle: 'தனிப்பட்ட தரவை வெளிப்படுத்தாமல் மருத்துவ அறிக்கைகளை சுருக்கவும்.',
    startSummarizing: 'சுருக்கத்தைத் தொடங்கு',
    viewDemo: 'டெமோவைப் பார்க்க',
    home: 'முகப்பு',
    features: 'அம்சங்கள்',
    howItWorks: 'இது எப்படி வேலை செய்கிறது',
    demo: 'டெமோ',
    security: 'பாதுகாப்பு',
    about: 'எங்களைப் பற்றி',
    login: 'உள்நுழைவு',
    settings: 'அமைவுகள்',
    profile: 'சுயவிவரம்',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    dashboard: 'டாஷ்போர்டு',
    trustBanner: 'நாங்கள் எப்போதும் மூல மருத்துவ பதிவுகளை சேமிப்பதில்லை.',
    trustSubtext: 'திருத்தப்பட்ட சுருக்கங்கள் மட்டுமே செயலாக்கப்படுகின்றன.',
    chipZeroStorage: 'பூஜ்ஜிய மூல தரவு சேமிப்பு',
    chipRedaction: 'கிளையன்ட்-பக்க திருத்தம்',
    chipCitations: 'விளக்கக்கூடிய மேற்கோள்கள்',
    product: 'தயாரிப்பு',
    resources: 'வளங்கள்',
    legal: 'சட்ட',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    contact: 'தொடர்பு',
    github: 'GitHub',
    terms: 'விதிமுறைகள்',
    data: 'தரவு',
    footerCopyright: '© 2026 சுகாதார சுருக்கி। அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை।',
  },
  gu: {
    appName: 'આરોગ્ય સારાંશક',
    tagline: 'ગોપનીયતા-સુરક્ષિત આરોગ્ય રેકોર્ડ સારાંશ',
    subtitle: 'વ્યક્તિગત ડેટા પ્રગટ કર્યા વિના તબીબી અહેવાલોનો સારાંશ આપો.',
    startSummarizing: 'સારાંશ શરૂ કરો',
    viewDemo: 'ડેમો જુઓ',
    home: 'હોમ',
    features: 'વિશેષતાઓ',
    howItWorks: 'આ કેવી રીતે કામ કરે છે',
    demo: 'ડેમો',
    security: 'સુરક્ષા',
    about: 'અમારી વિશે',
    login: 'લોગિન',
    settings: 'સેટિંગ્સ',
    profile: 'પ્રોફાઇલ',
    selectLanguage: 'ભાષા પસંદ કરો',
    dashboard: 'ડેશબોર્ડ',
    trustBanner: 'અમે ક્યારેય કાચા તબીબી રેકોર્ડ સંગ્રહિત કરતા નથી.',
    trustSubtext: 'ફક્ત સંપાદિત સારાંશ પ્રક્રિયા કરવામાં આવે છે.',
    chipZeroStorage: 'શૂન્ય કાચો ડેટા સંગ્રહ',
    chipRedaction: 'ક્લાયન્ટ-સાઇડ સંપાદન',
    chipCitations: 'સમજાવી શકાય તેવા ટાંકણો',
    product: 'ઉત્પાદન',
    resources: 'સંસાધનો',
    legal: 'કાનૂની',
    privacyPolicy: 'ગોપનીયતા નીતિ',
    contact: 'સંપર્ક',
    github: 'GitHub',
    terms: 'શરતો',
    data: 'ડેટા',
    footerCopyright: '© 2026 આરોગ્ય સારાંશક। બધા અધિકારો સુરક્ષિત છે।',
  },
  kn: {
    appName: 'ಆರೋಗ್ಯ ಸಾರಾಂಶಕಾರ',
    tagline: 'ಗೌಪ್ಯತೆ-ಸುರಕ್ಷಿತ ಆರೋಗ್ಯ ದಾಖಲೆ ಸಾರಾಂಶ',
    subtitle: 'ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ಬಹಿರಂಗಪಡಿಸದೆ ವೈದ್ಯಕೀಯ ವರದಿಗಳನ್ನು ಸಾರಾಂಶಗೊಳಿಸಿ.',
    startSummarizing: 'ಸಾರಾಂಶವನ್ನು ಪ್ರಾರಂಭಿಸಿ',
    viewDemo: 'ಡೆಮೋ ನೋಡಿ',
    home: 'ಮುಖಪುಟ',
    features: 'ವೈಶಿಷ್ಟ್ಯಗಳು',
    howItWorks: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    demo: 'ಡೆಮೋ',
    security: 'ಭದ್ರತೆ',
    about: 'ನಮ್ಮ ಬಗ್ಗೆ',
    login: 'ಲಾಗಿನ್',
    settings: 'ಸೆಟ್ಟಿಂಗ್ಸ್',
    profile: 'ಪ್ರೊಫೈಲ್',
    selectLanguage: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    trustBanner: 'ನಾವು ಎಂದಿಗೂ ಕಚ್ಚಾ ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳನ್ನು ಸಂಗ್ರಹಿಸುವುದಿಲ್ಲ.',
    trustSubtext: 'ಸಂಪಾದಿತ ಸಾರಾಂಶಗಳನ್ನು ಮಾತ್ರ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತದೆ.',
    chipZeroStorage: 'ಶೂನ್ಯ ಕಚ್ಚಾ ಡೇಟಾ ಸಂಗ್ರಹಣೆ',
    chipRedaction: 'ಕ್ಲೈಂಟ್-ಸೈಡ್ ಸಂಪಾದನೆ',
    chipCitations: 'ವಿವರಿಸಬಹುದಾದ ಉಲ್ಲೇಖಗಳು',
    product: 'ಉತ್ಪನ್ನ',
    resources: 'ಸಂಪನ್ಮೂಲಗಳು',
    legal: 'ಕಾನೂನು',
    privacyPolicy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    contact: 'ಸಂಪರ್ಕಿಸಿ',
    github: 'GitHub',
    terms: 'ನಿಯಮಗಳು',
    data: 'ಡೇಟಾ',
    footerCopyright: '© 2026 ಆರೋಗ್ಯ ಸಾರಾಂಶಕಾರ। ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ।',
  },
  ml: {
    appName: 'ആരോഗ്യ സംഗ്രഹകൻ',
    tagline: 'സ്വകാര്യത-സുരക്ഷിത ആരോഗ്യ രേഖ സംഗ്രഹം',
    subtitle: 'വ്യക്തിഗത ഡാറ്റ വെളിപ്പെടുത്താതെ മെഡിക്കൽ റിപ്പോർട്ടുകൾ സംഗ്രഹിക്കുക.',
    startSummarizing: 'സംഗ്രഹം ആരംഭിക്കുക',
    viewDemo: 'ഡെമോ കാണുക',
    home: 'ഹോം',
    features: 'സവിശേഷതകൾ',
    howItWorks: 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
    demo: 'ഡെമോ',
    security: 'സുരക്ഷ',
    about: 'ഞങ്ങളെക്കുറിച്ച്',
    login: 'ലോഗിൻ',
    settings: 'സെറ്റിങ്സ്',
    profile: 'പ്രൊഫൈൽ',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    dashboard: 'ഡാഷ്ബോർഡ്',
    trustBanner: 'ഞങ്ങൾ ഒരിക്കലും അസംസ്കൃത മെഡിക്കൽ രേഖകൾ സംഭരിക്കുന്നില്ല.',
    trustSubtext: 'എഡിറ്റ് ചെയ്ത സംഗ്രഹങ്ങൾ മാത്രമേ പ്രോസസ്സ് ചെയ്യപ്പെടുകയുള്ളൂ.',
    chipZeroStorage: 'പൂജ്യം അസംസ്കൃത ഡാറ്റ സംഭരണം',
    chipRedaction: 'ക്ലയന്റ്-സൈഡ് എഡിറ്റിംഗ്',
    chipCitations: 'വിശദീകരിക്കാവുന്ന ഉദ്ധരണികൾ',
    product: 'ഉൽപ്പന്നം',
    resources: 'വിഭവങ്ങൾ',
    legal: 'നിയമപരം',
    privacyPolicy: 'സ്വകാര്യതാ നയം',
    contact: 'ബന്ധപ്പെടുക',
    github: 'GitHub',
    terms: 'നിബന്ധനകൾ',
    data: 'ഡാറ്റ',
    footerCopyright: '© 2026 ആരോഗ്യ സംഗ്രഹകൻ। എല്ലാ അവകാശങ്ങളും സംരക്ഷിതം।',
  },
  pa: {
    appName: 'ਸਿਹਤ ਸੰਖੇਪਕ',
    tagline: 'ਗੋਪਨੀਯਤਾ-ਸੁਰੱਖਿਅਤ ਸਿਹਤ ਰਿਕਾਰਡ ਸੰਖੇਪ',
    subtitle: 'ਨਿੱਜੀ ਡੇਟਾ ਦਾ ਖੁਲਾਸਾ ਕੀਤੇ ਬਿਨਾਂ ਮੈਡੀਕਲ ਰਿਪੋਰਟਾਂ ਦਾ ਸਾਰ ਦਿਓ।',
    startSummarizing: 'ਸੰਖੇਪ ਸ਼ੁਰੂ ਕਰੋ',
    viewDemo: 'ਡੈਮੋ ਦੇਖੋ',
    home: 'ਹੋਮ',
    features: 'ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
    howItWorks: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
    demo: 'ਡੈਮੋ',
    security: 'ਸੁਰੱਖਿਆ',
    about: 'ਸਾਡੇ ਬਾਰੇ',
    login: 'ਲਾਗਿਨ',
    settings: 'ਸੈਟਿੰਗਜ਼',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    trustBanner: 'ਅਸੀਂ ਕਦੇ ਵੀ ਕੱਚੇ ਮੈਡੀਕਲ ਰਿਕਾਰਡ ਸਟੋਰ ਨਹੀਂ ਕਰਦੇ।',
    trustSubtext: 'ਸਿਰਫ਼ ਸੰਪਾਦਿਤ ਸੰਖੇਪ ਪ੍ਰਕਿਰਿਆ ਕੀਤੇ ਜਾਂਦੇ ਹਨ।',
    chipZeroStorage: 'ਜ਼ੀਰੋ ਕੱਚਾ ਡੇਟਾ ਸਟੋਰੇਜ',
    chipRedaction: 'ਕਲਾਇੰਟ-ਸਾਈਡ ਸੰਪਾਦਨ',
    chipCitations: 'ਵਿਆਖਿਆਯੋਗ ਹਵਾਲੇ',
    product: 'ਉਤਪਾਦ',
    resources: 'ਸਰੋਤ',
    legal: 'ਕਾਨੂੰਨੀ',
    privacyPolicy: 'ਗੋਪਨੀਯਤਾ ਨੀਤੀ',
    contact: 'ਸੰਪਰਕ',
    github: 'GitHub',
    terms: 'ਨਿਯਮ',
    data: 'ਡੇਟਾ',
    footerCopyright: '© 2026 ਸਿਹਤ ਸੰਖੇਪਕ। ਸਾਰੇ ਅਧਿਕਾਰ ਰਾਖਵੇਂ।',
  },
  or: {
    appName: 'ସ୍ୱାସ୍ଥ୍ୟ ସାରାଂଶକାରୀ',
    tagline: 'ଗୋପନୀୟତା-ସୁରକ୍ଷିତ ସ୍ୱାସ୍ଥ୍ୟ ରେକର୍ଡ ସାରାଂଶ',
    subtitle: 'ବ୍ୟକ୍ତିଗତ ତଥ୍ୟ ପ୍ରକାଶ ନକରି ଚିକିତ୍ସା ରିପୋର୍ଟଗୁଡ଼ିକୁ ସାରାଂଶ କରନ୍ତୁ।',
    startSummarizing: 'ସାରାଂଶ ଆରମ୍ଭ କରନ୍ତୁ',
    viewDemo: 'ଡେମୋ ଦେଖନ୍ତୁ',
    home: 'ହୋମ',
    features: 'ବୈଶିଷ୍ଟ୍ୟଗୁଡିକ',
    howItWorks: 'ଏହା କିପରି କାମ କରେ',
    demo: 'ଡେମୋ',
    security: 'ସୁରକ୍ଷା',
    about: 'ଆମ ବିଷୟରେ',
    login: 'ଲଗିନ୍',
    settings: 'ସେଟିଙ୍ସ',
    profile: 'ପ୍ରୋଫାଇଲ',
    selectLanguage: 'ଭାଷା ପସନ୍ଦ କରନ୍ତୁ',
    dashboard: 'ଡ୍ୟାସବୋର୍ଡ',
    trustBanner: 'ଆମେ କଦାପି କଞ୍ଚା ଚିକିତ୍ସା ରେକର୍ଡ ସଂରକ୍ଷଣ କରୁନାହୁଁ।',
    trustSubtext: 'କେବଳ ସମ୍ପାଦିତ ସାରାଂଶ ପ୍ରକ୍ରିୟାକରଣ କରାଯାଏ।',
    chipZeroStorage: 'ଶୂନ୍ୟ କଞ୍ଚା ତଥ୍ୟ ସଂରକ୍ଷଣ',
    chipRedaction: 'କ୍ଲାଏଣ୍ଟ-ସାଇଡ୍ ସମ୍ପାଦନା',
    chipCitations: 'ବ୍ୟାଖ୍ୟାଯୋଗ୍ୟ ଉଦ୍ଧୃତି',
    product: 'ଉତ୍ପାଦ',
    resources: 'ସମ୍ବଳଗୁଡିକ',
    legal: 'ଆଇନଗତ',
    privacyPolicy: 'ଗୋପନୀୟତା ନୀତି',
    contact: 'ଯୋଗାଯୋଗ',
    github: 'GitHub',
    terms: 'ସର୍ତ୍ତ',
    data: 'ତଥ୍ୟ',
    footerCopyright: '© 2026 ସ୍ୱାସ୍ଥ୍ୟ ସାରାଂଶକାରୀ। ସମସ୍ତ ଅଧିକାର ସଂରକ୍ଷିତ।',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const stored = localStorage.getItem('language') as Language;
    if (stored) setLanguage(stored);
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
